[unstable]
bindeps = true

[target.x86_64-unknown-none]
runner = [
    "cargo",
    "run",
    "--quiet",
    "--target-dir",
    "target/test-runner",
    "-p",
    "ghostos-test-runner",
    "--",
]

[alias]
ktest = "test -p kernel64 --target x86_64-unknown-none"
